POST http://localhost:8080/tasks
Accept: application/json
Content-Type: application/json

{
  "name": "Wyprowadź psa",
  "description": "Pies nazywa się Torent"
}

###

POST http://localhost:8080/tasks
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "description": "Pies nazywa się Torent"
}

###

GET http://localhost:8080/tasks
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/tasks/57644aa6-3a79-4faf-a12e-4a73d521e548
Accept: application/json
Content-Type: application/json

###

PUT http://localhost:8080/tasks/57644aa6-3a79-4faf-a12e-4a73d521e548?status=IN_PROGRESS
Accept: application/json
Content-Type: application/json

###

PUT http://localhost:8080/tasks/57644aa6-3a79-4faf-a12e-4a73d521e548?status=OH_NO
Accept: application/json
Content-Type: application/json