POST http://localhost:8080/tasks
Accept: application/json
Content-Type: application/json

{
  "name": "Wyprowadź psa",
  "description": "Pies nazywa się Torent"
}

###

GET http://localhost:8080/tasks
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/tasks/0a406954-a66f-4072-b3ec-f369524ed8ca
Accept: application/json
Content-Type: application/json
