POST http://localhost:8080/tasks
Accept: application/json
Content-Type: application/json

{
  "name": "Wyprowadź psa",
  "description": "Pies nazywa się Torent"
}

###

GET http://localhost:8080/tasks
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/tasks/1
Accept: application/json
Content-Type: application/json
