spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mytodo
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    #hibernate:
    #  ddl-auto: create-drop
    open-in-view: false
